# Generated by Django 4.2.7 on 2023-11-09 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avto',
            name='year',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
